### ISSUE TITLE
Please Tag a New Release

### ISSUE THREAD

**Issue by mcordingley** [ScaleDrone/scaledrone-php#3]
You have some commits that are over a year old, are quite probably good for release, but have only been made after the most recent release. Can you please tag a new release? You may also want to consider going ahead and marking the version as 1.0.0, since the project appears to be stable and so that clients can make use of the caret operator for version tracking. (e.g. "scaledrone/scaledrone": "^1.0.0")

**Comment by herkyl** [comment]
Hey @mcordingley, sorry for the late reply.

How exactly are you using Scaledrone. Are you using it through Composer? If so why do you need a new release in GitHub? You should be able to upgrade to 0.5.0 from packagist: https://packagist.org/packages/scaledrone/scaledrone

Regarding 1.0.0 I will keep this in mind for the future 👍

**Comment by mcordingley** [comment]
Used through Composer. I went ahead and just implemented my own version of this.
